name: Slack Version Notify

inputs:
  PACKAGE_VERSION:
    required: true
  SLACK_TOKEN:
    required: true
  SLACK_CHANNELS:
    required: true

runs:
  using: "composite"
  steps:
    - run: bash "${GITHUB_WORKSPACE}/.github/scripts/slack-notify.sh"
      shell: bash
      env:
          PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}
          SLACK_TOKEN: ${{ inputs.SLACK_TOKEN }}
          SLACK_CHANNELS: ${{ inputs.SLACK_CHANNELS }}
          TEST_PERMISSIONS : "1"
