name: Bump version

inputs:
  VERSION_TAG_NAME:
    required: true
    
runs:
  using: "composite"
  steps:
    - run: |
            npm install --no-package-lock --no-save semver@7.3.4
            PREV_PACKAGE_VERSION=$(node -p "require('./package.json').version")
            NEW_PACKAGE_VERSION=$(node ./.github/scripts/update-prerelease-version.js ${{ inputs.VERSION_TAG_NAME }})
            PACKAGE_VERSION=$(node -p "require('./package.json').version")
            echo "PACKAGE_VERSION=${NEW_PACKAGE_VERSION}" >> $GITHUB_ENV
            echo "PACKAGE_VERSION : ${PACKAGE_VERSION}"
      shell: bash
